# Wanderings through duckdb and polars

Findings: 
1. gosh this duckdb and polars stuff is fast.
2. now we get to figure out the useful views we need and we can work on the fast because parquet has modern bindings in so many places, from R to python.

In [ ]:
import duckdb 
import polars as pl

In [2]:
con = duckdb.connect()
con.execute("LOAD spatial")

In [3]:
parquet_path = "../out/national1825.parquet"

In [4]:

con.sql("""
    SELECT *
    FROM read_parquet($path)
    LIMIT 10
""", params={"path": parquet_path})

┌──────────┬─────────────────┬──────────┬────────────────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┬─────────┬──────────┬───────────────────┬──────────────┬──────────┬────────────────────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ OBJECTID │      CSBID      │ CSBYEARS │      CSBACRES      │ CDL2018 │ CDL2019 │ CDL2020 │ CDL2021 │ CDL2022 │ CDL2023 │ CDL2024 │ CDL2025 │ STATEFIPS │ STATEASD │   ASD   │  CNTY   │ CNTYFIPS │     INSIDE_X      │   INSIDE_Y   │ ORIG_FID │    Shape_Length    │     Shape_Area     │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Shape                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           │
│  int64   │     varchar     │ varchar  │       double       │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  varchar  │ varchar  │ varchar │ varchar │ varchar  │      double       │    double    │  int32   │       double       │       double       │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  geometry('epsg:5070')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │
├──────────┼─────────────────┼──────────┼────────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┼─────────┼──────────┼───────────────────┼──────────────┼──────────┼────────────────────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        1 │ 351825000000001 │ 1825     │  8.014266533798391 │      24 │      24 │      24 │      24 │      24 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -648193.3343 │ 1447136.6069 │     NULL │ 1094.6718033936615 │  32432.71572386057 │ MULTIPOLYGON (((-648233.7895 1447215.1187999994, -648105.5099 1447205.3157000002, -648103.2107999995 1447235.4035, -648071.1411000006 1447232.9530999996, -648076.5052000005 1447162.7481999993, -648108.5753000006 1447165.1986999996, -648137.2260999996 1447106.8610999994, -648144.8900000006 1447006.5687000006, -648225.0666000005 1447012.695699999, -648281.1904000007 1447016.9850999992, -648276.591 1447077.1604999993, -648244.5206000004 1447074.7094, -648239.1549999993 1447144.9141000006, -648271.2251999993 1447147.3652, -648268.9255999997 1447177.4529, -648263.5598000009 1447247.6576000005, -648258.1938000005 1447317.862400001, -648226.1245000008 1447315.4112999998, -648233.7895 1447215.1187999994)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      │
│        2 │ 351825000000002 │ 1825     │  5.775874123460195 │      24 │      24 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647571.4914 │ 1447063.6498 │     NULL │ 1164.5374695384517 │ 23374.226788312517 │ MULTIPOLYGON (((-647690.9452999998 1446931.5417, -647658.8743999992 1446929.0929000005, -647631.7579999994 1446967.3734000009, -647605.4077000003 1446995.6248000003, -647600.0473999996 1447065.8298000004, -647624.1002999991 1447067.6663000006, -647619.5055999998 1447127.8421, -647592.3900000006 1447166.1228999998, -647560.3199000005 1447163.6743, -647558.0227000006 1447193.7622999996, -647670.2675999999 1447202.3325999994, -647667.2041999996 1447242.4497999996, -647530.9075000007 1447232.0431999993, -647551.5809000004 1446961.2520000003, -647607.7049000002 1446965.5369000006, -647610.7678999994 1446925.4197000004, -647637.1184999999 1446897.1684000008, -647693.2429000009 1446901.4539, -647690.9452999998 1446931.5417)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 │
│        3 │ 351825000000003 │ 1825     │  5.206379494043526 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -647642.659499999 │ 1446862.2847 │     NULL │  760.5431722642115 │ 21069.554571055713 │ MULTIPOLYGON (((-647551.5809000004 1446961.2520000003, -647554.6436999999 1446921.1348, -647530.5903999992 1446919.2984999996, -647535.1842999998 1446859.1227000002, -647559.2377000004 1446860.9590000007, -647562.3004999999 1446820.8419000003, -647754.7285999991 1446835.5349000003, -647751.6649999991 1446875.6520000007, -647747.0694999993 1446935.8276000004, -647690.9452999998 1446931.5417, -647693.2429000009 1446901.4539, -647637.1184999999 1446897.1684000008, -647610.7678999994 1446925.4197000004, -647607.7049000002 1446965.5369000006, -647551.5809000004 1446961.2520000003)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 │

In [5]:
csb = pl.scan_parquet("../out/national1825.parquet")

csb.head(10).collect()

shape: (10, 23)
┌──────────┬────────────┬──────────┬───────────┬───┬──────────┬────────────┬───────────┬───────────┐
│ OBJECTID ┆ CSBID      ┆ CSBYEARS ┆ CSBACRES  ┆ … ┆ ORIG_FID ┆ Shape_Leng ┆ Shape_Are ┆ Shape     │
│ ---      ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---      ┆ th         ┆ a         ┆ ---       │
│ i64      ┆ str        ┆ str      ┆ f64       ┆   ┆ i32      ┆ ---        ┆ ---       ┆ binary    │
│          ┆            ┆          ┆           ┆   ┆          ┆ f64        ┆ f64       ┆           │
╞══════════╪════════════╪══════════╪═══════════╪═══╪══════════╪════════════╪═══════════╪═══════════╡
│ 1        ┆ 3518250000 ┆ 1825     ┆ 8.014267  ┆ … ┆ null     ┆ 1094.67180 ┆ 32432.715 ┆ b"\x01\x0 │
│          ┆ 00001      ┆          ┆           ┆   ┆          ┆ 3          ┆ 724       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 2        ┆ 3518250000 ┆ 1825     ┆ 5.775874  ┆ … ┆ null     ┆ 1164.53747 ┆ 23374.226 ┆ b"\x01\x0 │
│          ┆ 00002      ┆          ┆           ┆   ┆          ┆            ┆ 788       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 3        ┆ 3518250000 ┆ 1825     ┆ 5.206379  ┆ … ┆ null     ┆ 760.543172 ┆ 21069.554 ┆ b"\x01\x0 │
│          ┆ 00003      ┆          ┆           ┆   ┆          ┆            ┆ 571       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 4        ┆ 3518250000 ┆ 1825     ┆ 50.28417  ┆ … ┆ null     ┆ 2879.63998 ┆ 203493.63 ┆ b"\x01\x0 │
│          ┆ 00004      ┆          ┆           ┆   ┆          ┆ 5          ┆ 1663      ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 5        ┆ 3518250000 ┆ 1825     ┆ 24.592811 ┆ … ┆ null     ┆ 2484.03158 ┆ 99523.973 ┆ b"\x01\x0 │
│          ┆ 00005      ┆          ┆           ┆   ┆          ┆ 8          ┆ 574       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 6        ┆ 3518250000 ┆ 1825     ┆ 15.679466 ┆ … ┆ null     ┆ 1263.81515 ┆ 63452.800 ┆ b"\x01\x0 │
│          ┆ 00006      ┆          ┆           ┆   ┆          ┆ 7          ┆ 526       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 7        ┆ 3518250000 ┆ 1825     ┆ 5.626246  ┆ … ┆ null     ┆ 915.463428 ┆ 22768.700 ┆ b"\x01\x0 │
│          ┆ 00007      ┆          ┆           ┆   ┆          ┆            ┆ 256       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 8        ┆ 3518250000 ┆ 1825     ┆ 11.182569 ┆ … ┆ null     ┆ 1218.86497 ┆ 45254.431 ┆ b"\x01\x0 │
│          ┆ 00008      ┆          ┆           ┆   ┆          ┆ 4          ┆ 722       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 9        ┆ 3518250000 ┆ 1825     ┆ 32.228273 ┆ … ┆ null     ┆ 3108.09098 ┆ 130423.71 ┆ b"\x01\x0 │
│          ┆ 00009      ┆          ┆           ┆   ┆          ┆ 7          ┆ 615       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
│ 10       ┆ 3518250000 ┆ 1825     ┆ 7.615022  ┆ … ┆ null     ┆ 959.532892 ┆ 30817.024 ┆ b"\x01\x0 │
│          ┆ 00010      ┆          ┆           ┆   ┆          ┆            ┆ 512       ┆ 6\x00\x00 │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ \x00\x01\ │
│          ┆            ┆          ┆           ┆   ┆          ┆            ┆           ┆ x00…      │
└──────────┴────────────┴──────────┴───────────┴───┴──────────┴────────────┴───────────┴───────────┘

In [7]:
csb.columns

/var/folders/x8/45mkjqcx45l16ps8jqwlq7yw0000gn/T/ipykernel_75013/1537140931.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  csb.columns

['OBJECTID',
 'CSBID',
 'CSBYEARS',
 'CSBACRES',
 'CDL2018',
 'CDL2019',
 'CDL2020',
 'CDL2021',
 'CDL2022',
 'CDL2023',
 'CDL2024',
 'CDL2025',
 'STATEFIPS',
 'STATEASD',
 'ASD',
 'CNTY',
 'CNTYFIPS',
 'INSIDE_X',
 'INSIDE_Y',
 'ORIG_FID',
 'Shape_Length',
 'Shape_Area',
 'Shape']

In [27]:
tmp = None

tmp = csb.select(['OBJECTID',
 'CSBID',
 'CSBYEARS',
 'CSBACRES',
 'CDL2018',
 'CDL2019',
 'CDL2020',
 'CDL2021',
 'CDL2022',
 'CDL2023',
 'CDL2024',
 'CDL2025',
 'STATEFIPS',
 'STATEASD',
 'ASD',
 'CNTY',
 'CNTYFIPS',
 'INSIDE_X',
 'INSIDE_Y',
 'ORIG_FID',
 'Shape_Length',
 'Shape_Area',]).head(100).collect()

In [28]:
tmp

shape: (100, 22)
┌──────────┬────────────┬──────────┬───────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ OBJECTID ┆ CSBID      ┆ CSBYEARS ┆ CSBACRES  ┆ … ┆ INSIDE_Y ┆ ORIG_FID ┆ Shape_Leng ┆ Shape_Area │
│ ---      ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---      ┆ th         ┆ ---        │
│ i64      ┆ str        ┆ str      ┆ f64       ┆   ┆ f64      ┆ i32      ┆ ---        ┆ f64        │
│          ┆            ┆          ┆           ┆   ┆          ┆          ┆ f64        ┆            │
╞══════════╪════════════╪══════════╪═══════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ 1        ┆ 3518250000 ┆ 1825     ┆ 8.014267  ┆ … ┆ 1.4471e6 ┆ null     ┆ 1094.67180 ┆ 32432.7157 │
│          ┆ 00001      ┆          ┆           ┆   ┆          ┆          ┆ 3          ┆ 24         │
│ 2        ┆ 3518250000 ┆ 1825     ┆ 5.775874  ┆ … ┆ 1.4471e6 ┆ null     ┆ 1164.53747 ┆ 23374.2267 │
│          ┆ 00002      ┆          ┆           ┆   ┆          ┆          ┆            ┆ 88         │
│ 3        ┆ 3518250000 ┆ 1825     ┆ 5.206379  ┆ … ┆ 1.4469e6 ┆ null     ┆ 760.543172 ┆ 21069.5545 │
│          ┆ 00003      ┆          ┆           ┆   ┆          ┆          ┆            ┆ 71         │
│ 4        ┆ 3518250000 ┆ 1825     ┆ 50.28417  ┆ … ┆ 1.4471e6 ┆ null     ┆ 2879.63998 ┆ 203493.631 │
│          ┆ 00004      ┆          ┆           ┆   ┆          ┆          ┆ 5          ┆ 663        │
│ 5        ┆ 3518250000 ┆ 1825     ┆ 24.592811 ┆ … ┆ 1.4471e6 ┆ null     ┆ 2484.03158 ┆ 99523.9735 │
│          ┆ 00005      ┆          ┆           ┆   ┆          ┆          ┆ 8          ┆ 74         │
│ …        ┆ …          ┆ …        ┆ …         ┆ … ┆ …        ┆ …        ┆ …          ┆ …          │
│ 96       ┆ 3518250000 ┆ 1825     ┆ 9.928489  ┆ … ┆ 1.4432e6 ┆ null     ┆ 1247.57557 ┆ 40179.3305 │
│          ┆ 00096      ┆          ┆           ┆   ┆          ┆          ┆ 7          ┆ 73         │
│ 97       ┆ 3518250000 ┆ 1825     ┆ 8.208686  ┆ … ┆ 1.4433e6 ┆ null     ┆ 930.153706 ┆ 33219.5054 │
│          ┆ 00097      ┆          ┆           ┆   ┆          ┆          ┆            ┆ 66         │
│ 98       ┆ 3518250000 ┆ 1825     ┆ 6.099102  ┆ … ┆ 1.4432e6 ┆ null     ┆ 1038.66729 ┆ 24682.2893 │
│          ┆ 00098      ┆          ┆           ┆   ┆          ┆          ┆            ┆ 07         │
│ 99       ┆ 3518250000 ┆ 1825     ┆ 10.788312 ┆ … ┆ 1.4434e6 ┆ null     ┆ 844.679634 ┆ 43658.9253 │
│          ┆ 00099      ┆          ┆           ┆   ┆          ┆          ┆            ┆ 77         │
│ 100      ┆ 3518250000 ┆ 1825     ┆ 24.096261 ┆ … ┆ 1.4432e6 ┆ null     ┆ 1578.93721 ┆ 97514.4976 │
│          ┆ 00100      ┆          ┆           ┆   ┆          ┆          ┆            ┆ 4          │
└──────────┴────────────┴──────────┴───────────┴───┴──────────┴──────────┴────────────┴────────────┘

tmp

In [29]:
# tmp.write_csv("../out/tmp.csv")

# this makes a nearly useless csv dont do this.

In [21]:
pl.build_info()

{'version': '1.44.2'}

In [23]:
pl.thread_pool_size()

8